# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

tests = Test.create!([
  { testtype: 'SAT' },
  { testtype: 'ACT' },
  { testtype: 'IELTS'},
  { testtype: 'TOEFL'},
  { testtype: 'SSAT'}
])

Testinstance.create!([
  { name: 'SAT CRAM 1', test: Test.where("testtype = 'SAT'").first },
  { name: 'SAT CRAM 2', test: Test.where("testtype = 'SAT'").first },
  { name: 'SAT CRAM 3', test: Test.where("testtype = 'SAT'").first },
  { name: 'SAT CRAM 4', test: Test.where("testtype = 'SAT'").first },
  { name: 'ACT CRAM 1', test: Test.where("testtype = 'ACT'").first },
  { name: 'ACT CRAM 2', test: Test.where("testtype = 'ACT'").first },
  { name: 'ACT CRAM 3', test: Test.where("testtype = 'ACT'").first },
  { name: 'ACT CRAM 4', test: Test.where("testtype = 'ACT'").first }
])

# Testsection.create!([
#   { name: 'Section 1: Reading Test', test: Test.where("testtype = 'SAT'").first },
#   { name: 'Section 2: Writing & Language Test', test: Test.where("testtype = 'SAT'").first },
#   { name: 'Section 3: Math Test - No Calculator ', test: Test.where("testtype = 'SAT'").first },
#   { name: 'Section 4: Math Test - Calculator ', test: Test.where("testtype = 'SAT'").first },
#   { name: 'Section 1: English Test ', test: Test.where("testtype = 'ACT'").first },
#   { name: 'Section 2: Mathematics Test ', test: Test.where("testtype = 'ACT'").first },
#   { name: 'Section 3: Reading Test ', test: Test.where("testtype = 'ACT'").first },
#   { name: 'Section 4: Science Test ', test: Test.where("testtype = 'ACT'").first },
# ])

Question.create!([
  { question_number: 1, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 2, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 3, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 4, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 5, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 6, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 7, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 8, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 9, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 10, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 11, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 12, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 13, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 14, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 15, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 16, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 17, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 18, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 19, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 20, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 21, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 22, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 23, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 24, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 25, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 26, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 27, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 28, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 29, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 30, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 31, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 32, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 33, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 34, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 35, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 36, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 37, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 38, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 39, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 40, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 41, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 42, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 43, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 44, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 45, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 46, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 47, answer: 'C', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 48, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 49, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 50, answer: 'D', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 51, answer: 'A', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 52, answer: 'B', section: 'Section 1: Reading Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  # Writing
  { question_number: 1, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 2, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 3, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 4, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 5, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 6, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 7, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 8, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 9, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 10, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 11, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 12, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 13, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 14, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 15, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 16, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 17, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 18, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 19, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 20, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 21, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 22, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 23, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 24, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 25, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 26, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 27, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 28, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 29, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 30, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 31, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 32, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 33, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 34, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 35, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 36, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 37, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 38, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 39, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 40, answer: 'A', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 41, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 42, answer: 'D', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 43, answer: 'C', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 44, answer: 'B', section: 'Section 2: Writing & Language Test', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  #Math-No Calc
  { question_number: 1, answer: 'B', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 2, answer: 'C', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 3, answer: 'C', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 4, answer: 'A', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 5, answer: 'B', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 6, answer: 'B', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 7, answer: 'A', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 8, answer: 'D', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 9, answer: 'A', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 10, answer: 'D', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 11, answer: 'D', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 12, answer: 'D', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 13, answer: 'C', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 14, answer: 'B', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 15, answer: 'C', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 16, answer: '15', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 17, answer: '10.5 OR 21/2', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 18, answer: '4', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 19, answer: '10', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 20, answer: '50.5', section: 'Section 3: Math Test - No Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  #Math Calc
  { question_number: 1, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 2, answer: 'B', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 3, answer: 'C', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 4, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 5, answer: 'C', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 6, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 7, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 8, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 9, answer: 'C', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 10, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 11, answer: 'B', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 12, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 13, answer: 'C', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 14, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 15, answer: 'B', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 16, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 17, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 18, answer: 'B', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 19, answer: 'C', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 20, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 21, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 22, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 23, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 24, answer: 'B', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 25, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 26, answer: 'B', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 27, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 28, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 29, answer: 'D', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 30, answer: 'A', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 31, answer: '9/26 OR 0.346', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 32, answer: '4', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 33, answer: '801', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 34, answer: '2/3 OR 0.666 OR 0.667', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 35, answer: '3.5 OR 7.2', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 36, answer: '3/10', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 37, answer: '3', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
  { question_number: 38, answer: '9.4', section: 'Section 4: Math Test - Calculator', testinstance: Testinstance.where("name = 'SAT CRAM 1'").first },
])